import type { AnalysisResult, Product } from '../types/signals'

export const MOCK_PRODUCTS: Product[] = [
  {
    asin: 'B0GD7BF2TZ',
    name: '4" 蓝白海绵床垫 Queen',
    category: '寝具',
    marketplace: 'US',
    status: 'active',
    stage: 'growth',
    signal_count_p0: 2,
    signal_count_p1: 1,
    health_score: 55,
  },
  {
    asin: 'B0FJKNRNZK',
    name: '150PSI 便携式电动充气泵',
    category: '汽车用品',
    marketplace: 'US',
    status: 'active',
    stage: 'early',
    signal_count_p0: 0,
    signal_count_p1: 2,
    health_score: 71,
  },
]

export const MOCK_ANALYSIS: AnalysisResult = {
  asin: 'B0GD7BF2TZ',
  product_name: '4" 蓝白海绵床垫 Queen',
  date_range: '2026-03-14 — 03-20',
  generated_at: '2026-03-21T08:00:00Z',
  metrics: {
    weekly_spend: 3658,
    weekly_sales: 6218,
    acos: 58.8,
    organic_ratio: 38,
    ad_ratio: 62,
    potential_weekly_savings: 220,
    spend_wow_change: 12,
    sales_wow_change: 8,
    acos_wow_change: 3.2,
  },
  health: {
    overall: 55,
    conversion: 70,
    budget_efficiency: 62,
    traffic_quality: 58,
    keyword_structure: 50,
    ad_efficiency: 35,
    wow_change: -4,
  },
  context: {
    stage: 'growth',
    bsr_main: 312,
    bsr_main_category: 'Furniture › Sofa Beds',
    bsr_sub: 2841,
    bsr_sub_category: 'Home & Kitchen',
    bsr_trend: 'up',
    inventory_days: 28,
    inventory_status: 'warning',
    inbound_qty: 480,
    inbound_eta: '4/12',
    daily_velocity: 6.2,
  },
  signals: [
    {
      signal_id: 'sig_p0_1',
      priority: 'P0',
      title: '精确匹配组 4 个词持续烧钱，本周无效消耗 $184，已连续 3 周零成交',
      description: '累计烧损超过 $400，每多等一周损失约 $150，建议今日执行暂停',
      timeline: [
        { week: 'W6', label: 'W6 无效花费', value: '$118', note: '3周前' },
        { week: 'W7', label: 'W7 无效花费', value: '$142', note: '2周前' },
        { week: 'W8', label: 'W8 无效花费', value: '$184', note: '本周' },
        { week: '累计', label: '3周累计损失', value: '$444', note: '已超止损阈值' },
      ],
      evidence_headers: ['关键词', '匹配', '点击', '花费', '成交', '广泛组表现', '建议'],
      evidence_table: [
        { '关键词': 'sleeper sofa mattress', '匹配': '精确', '点击': '50', '花费': '$87', '成交': '0', '广泛组表现': 'ACOS 53%，有效', '建议': '暂停' },
        { '关键词': 'sofa bed mattress replacement', '匹配': '精确', '点击': '29', '花费': '$52', '成交': '0', '广泛组表现': '无数据', '建议': '暂停' },
        { '关键词': 'sofa mattress（精确）', '匹配': '精确', '点击': '24', '花费': '$45', '成交': '0', '广泛组表现': '广泛组有转化', '建议': '暂停' },
        { '关键词': 'mattress for sofa bed', '匹配': '精确', '点击': '23', '花费': '$38', '成交': '0', '广泛组表现': '少量数据', '建议': '降至 $0.80 观察' },
      ],
      reasoning: '<strong>判断依据：</strong>精确匹配词超 30 次点击零转化，在亚马逊广告中属于"确认无效"阈值。这三个词在广泛匹配组已有成交记录（ACOS 50-53%），说明产品本身对这个搜索意图有转化能力，精确组无转化的原因可能是竞价位置差或listing展示问题，但已不值得继续测试。<strong>止损 $150/周不是小数字——相当于每年 $7,800 的纯浪费。</strong>',
      financial_impact: { weekly_loss_usd: 184, weekly_gain_usd: 0, description: '暂停后每周节省 ~$184' },
      actions: [
        { title: '生成操作步骤', prompt: '生成暂停sleeper sofa mattress、sofa bed mattress replacement、sofa mattress精确匹配组的完整操作步骤，包含在哪个后台菜单操作', style: 'primary' },
        { title: '核实广泛组数据', prompt: '这4个词在广泛匹配组的历史转化数据是什么？帮我确认广泛组确实有效', style: 'default' },
      ],
      related_ad_groups: ['FIX_EX', 'MANU_KW'],
    },
    {
      signal_id: 'sig_p0_2',
      priority: 'P0',
      title: '新广告组 ACOS 98%，sofa mattress 广泛词 23 次点击零成交，正在消耗预算',
      description: 'FIX_BRO 新组本周花费 $214，销售仅 $218，几乎打平且还在恶化',
      timeline: [
        { week: 'W8', label: '本组 ACOS', value: '98%', note: '目标 <55%' },
        { week: 'W8', label: '主力广泛组 ACOS', value: '53%', note: '同词，效率更高' },
        { week: 'W8', label: '本组无效消耗', value: '$37', note: 'sofa mattress 广泛' },
        { week: 'W8', label: 'sleeper sofa mattress', value: 'ACOS 81%', note: 'CTR 2.42% 尚可' },
      ],
      evidence_headers: [],
      evidence_table: [],
      reasoning: '<strong>为什么 98% 的 ACOS 是危险信号：</strong>这个广告组与主力广泛组存在关键词重叠，两组互相竞价会抬高 CPC。主力组同词 ACOS 53%，本组 98%，说明本组竞价处于劣势位置。应先暂停 sofa mattress 广泛词，sleeper sofa mattress 出价从 $1.50 降至 $1.00 后观察 2 周，评估是否能独立运行或与主力组合并。',
      financial_impact: { weekly_loss_usd: 37, weekly_gain_usd: 0, description: '暂停无效词节省 ~$37/周' },
      actions: [
        { title: '分析合并方案', prompt: 'FIX_BRO新组与主力广泛组存在词重叠，给出合并方案或差异化运营方案', style: 'primary' },
      ],
      related_ad_groups: ['FIX_BRO'],
    },
    {
      signal_id: 'sig_p1_1',
      priority: 'P1',
      title: '主力广泛组 ACOS 已连续 3 周高于目标，根本原因是否定词未清理',
      description: '12 万曝光量从未拉过搜索词报告，估算 25% 流向无关搜索词',
      timeline: [
        { week: 'W5', label: 'W5 ACOS', value: '50%', note: '目标水位' },
        { week: 'W6', label: 'W6 ACOS', value: '53%', note: '开始上升' },
        { week: 'W7', label: 'W7 ACOS', value: '55%', note: '持续' },
        { week: 'W8', label: 'W8 ACOS', value: '58.8%', note: '本周，+8.8pt' },
      ],
      evidence_headers: ['关键词', '当前出价', '建议出价', '原因'],
      evidence_table: [
        { '关键词': 'queen sleeper sofa mattress', '当前出价': '$1.60', '建议出价': '$0.80', '原因': 'ACOS 114%，严重亏损' },
        { '关键词': 'queen sofa bed mattress', '当前出价': '$1.85', '建议出价': '$1.50', '原因': 'ACOS 68%，偏高' },
        { '关键词': 'sofa mattress 广泛', '当前出价': '$0.80', '建议出价': '$1.00–1.20', '原因': '出价偏低，展示量不足' },
      ],
      reasoning: '<strong>降 ACOS 最快手段：</strong>否定词清理效果通常快于出价调整。12 万曝光量从未清理过，按类目均值估算有 20–30% 流向不相关搜索（如 "sofa"、"mattress pad" 等宽泛词）。每清理一批否定词，CVR 预计提升 0.5–1pt，ACOS 对应下降 3–5pt。',
      financial_impact: { weekly_loss_usd: 0, weekly_gain_usd: 150, description: '否定词清理后预计 ACOS 下降 3–5pt' },
      actions: [
        { title: '查看否定词操作', prompt: '教我如何下载亚马逊广泛匹配搜索词报告，以及判断哪些词应该加入否定的标准', style: 'primary' },
        { title: '测算降价影响', prompt: 'queen sleeper sofa mattress出价从1.60降至0.80，预计每天减少多少曝光和点击', style: 'default' },
      ],
      related_ad_groups: ['MANU_BRD'],
    },
    {
      signal_id: 'sig_p2_1',
      priority: 'P2',
      title: '两个广告组对同一词出价相同，存在内部竞争，正在互相抬高 CPC',
      description: 'pull out couch mattress 精确词同时在 FIX_EX 与 MANU_KW 两组中竞价',
      timeline: [],
      evidence_headers: ['广告组', '出价', 'ACOS', 'CVR', '建议保留'],
      evidence_table: [
        { '广告组': 'MANU_KW pull out couch', '出价': '$1.50', 'ACOS': '35%', 'CVR': '4.0%', '建议保留': '保留' },
        { '广告组': 'FIX_EX pull out couch', '出价': '$1.50', 'ACOS': '40%', 'CVR': '3.7%', '建议保留': '考虑合并' },
      ],
      reasoning: '两组出价完全相同时，亚马逊系统视为同一广告主内部竞价，会随机分配展示，导致实际 CPC 高于应有水平。建议保留 ACOS 更低的 MANU_KW 组，FIX_EX 组中的重复词暂停，预算合并后加码出价到 $1.70 争取更好位置。',
      financial_impact: { weekly_loss_usd: 36, weekly_gain_usd: 0, description: '消除内部竞价节省 ~$36/周' },
      actions: [
        { title: '分析合并步骤', prompt: '分析pull out couch mattress两个广告组合并的具体步骤，合并后预算应该如何重新分配', style: 'primary' },
      ],
      related_ad_groups: ['FIX_EX', 'MANU_KW'],
    },
    {
      signal_id: 'sig_good_1',
      priority: 'good',
      title: '发现 2 个高效词，CVR 远超类目均值，预算充足时可加码放大',
      description: 'mattress for sleeper sofa ACOS 26% · CVR 6.9%，是当前最优词',
      timeline: [],
      evidence_headers: ['关键词', 'ACOS', 'CVR', '当前出价', '建议出价', '预期效果'],
      evidence_table: [
        { '关键词': 'mattress for sleeper sofa', 'ACOS': '26%', 'CVR': '6.9%', '当前出价': '$1.80', '建议出价': '$2.20', '预期效果': '销售额 +30–50%' },
        { '关键词': 'pull out couch mattress', 'ACOS': '35–40%', 'CVR': '3.7–4.0%', '当前出价': '$1.50', '建议出价': '$1.70', '预期效果': '销售额 +20–30%' },
      ],
      reasoning: '<strong>注意前置条件：</strong>当前库存可售天数 28 天，在途库存 4/12 到仓。加码广告会加速销售，建议等库存补充到位（4/12 之后）再执行提价，否则可能引发断货并导致 BSR 排名下滑，得不偿失。',
      financial_impact: { weekly_loss_usd: 0, weekly_gain_usd: 300, description: '加码后预计销售额每周增加 $300+' },
      actions: [
        { title: '测算加码效果', prompt: 'mattress for sleeper sofa出价从1.80提至2.20，按当前CVR 6.9%测算每天预期增加多少销售额和花费', style: 'primary' },
      ],
      related_ad_groups: ['MANU_KW'],
    },
  ],
}

export const MOCK_ACOS_TREND = [
  { week: 'W1', acos: 55, hasDecision: false },
  { week: 'W2', acos: 52, hasDecision: false },
  { week: 'W3', acos: 50, hasDecision: true },
  { week: 'W4', acos: 54, hasDecision: false },
  { week: 'W5', acos: 50, hasDecision: false },
  { week: 'W6', acos: 53, hasDecision: false },
  { week: 'W7', acos: 55, hasDecision: false },
  { week: 'W8', acos: 58.8, hasDecision: true },
]

export const MOCK_COMPETITORS = [
  { brand: 'EGOHOME', click_share: 15.4, delta: 1.2, is_self: false },
  { brand: 'Novilla', click_share: 11.1, delta: 0.1, is_self: false },
  { brand: 'FDW', click_share: 8.9, delta: -0.5, is_self: false },
  { brand: 'Zinus', click_share: 6.5, delta: -0.8, is_self: false },
  { brand: '本品', click_share: 4.6, delta: 0.3, is_self: true },
  { brand: 'Best Price', click_share: 3.9, delta: 0.0, is_self: false },
]
